import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--md-sys-color-primary)',
        'on-primary': 'var(--md-sys-color-on-primary)',
        'primary-container': 'var(--md-sys-color-primary-container)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        'on-secondary': 'var(--md-sys-color-on-secondary)',
        'secondary-container': 'var(--md-sys-color-secondary-container)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        'on-tertiary': 'var(--md-sys-color-on-tertiary)',
        error: 'var(--md-sys-color-error)',
        'on-error': 'var(--md-sys-color-on-error)',
        surface: 'var(--md-sys-color-surface)',
        'on-surface': 'var(--md-sys-color-on-surface)',
        'surface-variant': 'var(--md-sys-color-surface-variant)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'surface-container-low': 'var(--md-sys-color-surface-container-low)',
        'surface-container': 'var(--md-sys-color-surface-container)',
        'surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
        background: 'var(--md-sys-color-background)',
        'on-background': 'var(--md-sys-color-on-background)',
        outline: 'var(--md-sys-color-outline)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        'inverse-surface': 'var(--md-sys-color-inverse-surface)',
        'inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
        'inverse-primary': 'var(--md-sys-color-inverse-primary)',
        success: 'var(--md-sys-color-success)',
        'on-success': 'var(--md-sys-color-on-success)',
        'success-container': 'var(--md-sys-color-success-container)',
        'on-success-container': 'var(--md-sys-color-on-success-container)',
        warning: 'var(--md-sys-color-warning)',
        'on-warning': 'var(--md-sys-color-on-warning)',
        'warning-container': 'var(--md-sys-color-warning-container)',
        'on-warning-container': 'var(--md-sys-color-on-warning-container)',
        info: 'var(--md-sys-color-info)',
        'on-info': 'var(--md-sys-color-on-info)',
        'info-container': 'var(--md-sys-color-info-container)',
        'on-info-container': 'var(--md-sys-color-on-info-container)',
      },
      fontFamily: {
        brand: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
        plain: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s var(--md-ref-motion-easing-emphasized-decelerate) forwards',
      },
      fontSize: {
        'display-large': ['var(--md-sys-typescale-display-large-size)', { lineHeight: 'var(--md-sys-typescale-display-large-line-height)', letterSpacing: 'var(--md-sys-typescale-display-large-letter-spacing)', fontWeight: 'var(--md-sys-typescale-display-large-weight)' }],
        'display-medium': ['var(--md-sys-typescale-display-medium-size)', { lineHeight: 'var(--md-sys-typescale-display-medium-line-height)', letterSpacing: 'var(--md-sys-typescale-display-medium-letter-spacing)', fontWeight: 'var(--md-sys-typescale-display-medium-weight)' }],
        'display-small': ['var(--md-sys-typescale-display-small-size)', { lineHeight: 'var(--md-sys-typescale-display-small-line-height)', letterSpacing: 'var(--md-sys-typescale-display-small-letter-spacing)', fontWeight: 'var(--md-sys-typescale-display-small-weight)' }],
        'headline-large': ['var(--md-sys-typescale-headline-large-size)', { lineHeight: 'var(--md-sys-typescale-headline-large-line-height)', letterSpacing: 'var(--md-sys-typescale-headline-large-letter-spacing)', fontWeight: 'var(--md-sys-typescale-headline-large-weight)' }],
        'headline-medium': ['var(--md-sys-typescale-headline-medium-size)', { lineHeight: 'var(--md-sys-typescale-headline-medium-line-height)', letterSpacing: 'var(--md-sys-typescale-headline-medium-letter-spacing)', fontWeight: 'var(--md-sys-typescale-headline-medium-weight)' }],
        'headline-small': ['var(--md-sys-typescale-headline-small-size)', { lineHeight: 'var(--md-sys-typescale-headline-small-line-height)', letterSpacing: 'var(--md-sys-typescale-headline-small-letter-spacing)', fontWeight: 'var(--md-sys-typescale-headline-small-weight)' }],
        'title-large': ['var(--md-sys-typescale-title-large-size)', { lineHeight: 'var(--md-sys-typescale-title-large-line-height)', letterSpacing: 'var(--md-sys-typescale-title-large-letter-spacing)', fontWeight: 'var(--md-sys-typescale-title-large-weight)' }],
        'title-medium': ['var(--md-sys-typescale-title-medium-size)', { lineHeight: 'var(--md-sys-typescale-title-medium-line-height)', letterSpacing: 'var(--md-sys-typescale-title-medium-letter-spacing)', fontWeight: 'var(--md-sys-typescale-title-medium-weight)' }],
        'title-small': ['var(--md-sys-typescale-title-small-size)', { lineHeight: 'var(--md-sys-typescale-title-small-line-height)', letterSpacing: 'var(--md-sys-typescale-title-small-letter-spacing)', fontWeight: 'var(--md-sys-typescale-title-small-weight)' }],
        'body-large': ['var(--md-sys-typescale-body-large-size)', { lineHeight: 'var(--md-sys-typescale-body-large-line-height)', letterSpacing: 'var(--md-sys-typescale-body-large-letter-spacing)', fontWeight: 'var(--md-sys-typescale-body-large-weight)' }],
        'body-medium': ['var(--md-sys-typescale-body-medium-size)', { lineHeight: 'var(--md-sys-typescale-body-medium-line-height)', letterSpacing: 'var(--md-sys-typescale-body-medium-letter-spacing)', fontWeight: 'var(--md-sys-typescale-body-medium-weight)' }],
        'body-small': ['var(--md-sys-typescale-body-small-size)', { lineHeight: 'var(--md-sys-typescale-body-small-line-height)', letterSpacing: 'var(--md-sys-typescale-body-small-letter-spacing)', fontWeight: 'var(--md-sys-typescale-body-small-weight)' }],
        'label-large': ['var(--md-sys-typescale-label-large-size)', { lineHeight: 'var(--md-sys-typescale-label-large-line-height)', letterSpacing: 'var(--md-sys-typescale-label-large-letter-spacing)', fontWeight: 'var(--md-sys-typescale-label-large-weight)' }],
        'label-medium': ['var(--md-sys-typescale-label-medium-size)', { lineHeight: 'var(--md-sys-typescale-label-medium-line-height)', letterSpacing: 'var(--md-sys-typescale-label-medium-letter-spacing)', fontWeight: 'var(--md-sys-typescale-label-medium-weight)' }],
        'label-small': ['var(--md-sys-typescale-label-small-size)', { lineHeight: 'var(--md-sys-typescale-label-small-line-height)', letterSpacing: 'var(--md-sys-typescale-label-small-letter-spacing)', fontWeight: 'var(--md-sys-typescale-label-small-weight)' }],
        'caption': ['var(--md-sys-typescale-caption-size)', { lineHeight: 'var(--md-sys-typescale-caption-line-height)', letterSpacing: 'var(--md-sys-typescale-caption-letter-spacing)', fontWeight: '400' }],
      },
      spacing: {
        'm3-none': 'var(--md-sys-spacing-none)',
        'm3-xxx-small': 'var(--md-sys-spacing-xxx-small)',
        'm3-xx-small': 'var(--md-sys-spacing-xx-small)',
        'm3-x-small': 'var(--md-sys-spacing-x-small)',
        'm3-small': 'var(--md-sys-spacing-small)',
        'm3-medium': 'var(--md-sys-spacing-medium)',
        'm3-large': 'var(--md-sys-spacing-large)',
        'm3-x-large': 'var(--md-sys-spacing-x-large)',
        'm3-xx-large': 'var(--md-sys-spacing-xx-large)',
        'm3-xxx-large': 'var(--md-sys-spacing-xxx-large)',
        'm3-xxxx-large': 'var(--md-sys-spacing-xxxx-large)',
        'm3-5xl': 'var(--md-sys-spacing-5xl)',
        'm3-6xl': 'var(--md-sys-spacing-6xl)',
        'm3-7xl': 'var(--md-sys-spacing-7xl)',
      },
      borderRadius: {
        'm3-none': 'var(--md-sys-shape-corner-none)',
        'm3-xs': 'var(--md-sys-shape-corner-extra-small)',
        'm3-sm': 'var(--md-sys-shape-corner-small)',
        'm3-md': 'var(--md-sys-shape-corner-medium)',
        'm3-lg': 'var(--md-sys-shape-corner-large)',
        'm3-xl': 'var(--md-sys-shape-corner-extra-large)',
        'm3-full': 'var(--md-sys-shape-corner-full)',
      },
      boxShadow: {
        'm3-0': 'var(--md-sys-elevation-level-0)',
        'm3-1': 'var(--md-sys-elevation-level-1)',
        'm3-2': 'var(--md-sys-elevation-level-2)',
        'm3-3': 'var(--md-sys-elevation-level-3)',
        'm3-4': 'var(--md-sys-elevation-level-4)',
        'm3-5': 'var(--md-sys-elevation-level-5)',
      },
      transitionDuration: {
        'm3-short-1': 'var(--md-ref-motion-duration-short-1)',
        'm3-short-2': 'var(--md-ref-motion-duration-short-2)',
        'm3-medium-1': 'var(--md-ref-motion-duration-medium-1)',
        'm3-medium-2': 'var(--md-ref-motion-duration-medium-2)',
        'm3-long-1': 'var(--md-ref-motion-duration-long-1)',
        'm3-long-2': 'var(--md-ref-motion-duration-long-2)',
      },
      transitionTimingFunction: {
        'm3-emphasized': 'var(--md-ref-motion-easing-emphasized)',
        'm3-standard': 'var(--md-ref-motion-easing-standard)',
        'm3-linear': 'var(--md-ref-motion-easing-linear)',
      },
    },
  },
  plugins: [],
};

export default config;
