import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--md-sys-color-primary)',
        'on-primary': 'var(--md-sys-color-on-primary)',
        'primary-container': 'var(--md-sys-color-primary-container)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        'on-secondary': 'var(--md-sys-color-on-secondary)',
        'secondary-container': 'var(--md-sys-color-secondary-container)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        'on-tertiary': 'var(--md-sys-color-on-tertiary)',
        error: 'var(--md-sys-color-error)',
        'on-error': 'var(--md-sys-color-on-error)',
        surface: 'var(--md-sys-color-surface)',
        'on-surface': 'var(--md-sys-color-on-surface)',
        'surface-variant': 'var(--md-sys-color-surface-variant)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'surface-container-low': 'var(--md-sys-color-surface-container-low)',
        'surface-container': 'var(--md-sys-color-surface-container)',
        'surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
        background: 'var(--md-sys-color-background)',
        'on-background': 'var(--md-sys-color-on-background)',
        outline: 'var(--md-sys-color-outline)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        'inverse-surface': 'var(--md-sys-color-inverse-surface)',
        'inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
        'inverse-primary': 'var(--md-sys-color-inverse-primary)',
      },
      fontFamily: {
        brand: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
        plain: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'display-large': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'display-medium': ['45px', { lineHeight: '52px', letterSpacing: '0', fontWeight: '400' }],
        'display-small': ['36px', { lineHeight: '44px', letterSpacing: '0', fontWeight: '400' }],
        'headline-large': ['32px', { lineHeight: '40px', letterSpacing: '0', fontWeight: '400' }],
        'headline-medium': ['28px', { lineHeight: '36px', letterSpacing: '0', fontWeight: '400' }],
        'headline-small': ['24px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '400' }],
        'title-large': ['22px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'title-medium': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
        'title-small': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'body-large': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'body-small': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
        'label-large': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'label-medium': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'label-small': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '400' }],
      },
      borderRadius: {
        'm3-none': 'var(--md-sys-shape-corner-none)',
        'm3-xs': 'var(--md-sys-shape-corner-extra-small)',
        'm3-sm': 'var(--md-sys-shape-corner-small)',
        'm3-md': 'var(--md-sys-shape-corner-medium)',
        'm3-lg': 'var(--md-sys-shape-corner-large)',
        'm3-xl': 'var(--md-sys-shape-corner-extra-large)',
        'm3-full': 'var(--md-sys-shape-corner-full)',
      },
      boxShadow: {
        'm3-0': 'var(--md-sys-elevation-level-0)',
        'm3-1': 'var(--md-sys-elevation-level-1)',
        'm3-2': 'var(--md-sys-elevation-level-2)',
        'm3-3': 'var(--md-sys-elevation-level-3)',
        'm3-4': 'var(--md-sys-elevation-level-4)',
        'm3-5': 'var(--md-sys-elevation-level-5)',
      },
      transitionDuration: {
        'm3-short-1': 'var(--md-ref-motion-duration-short-1)',
        'm3-short-2': 'var(--md-ref-motion-duration-short-2)',
        'm3-medium-1': 'var(--md-ref-motion-duration-medium-1)',
        'm3-medium-2': 'var(--md-ref-motion-duration-medium-2)',
        'm3-long-1': 'var(--md-ref-motion-duration-long-1)',
        'm3-long-2': 'var(--md-ref-motion-duration-long-2)',
      },
      transitionTimingFunction: {
        'm3-emphasized': 'var(--md-ref-motion-easing-emphasized)',
        'm3-standard': 'var(--md-ref-motion-easing-standard)',
        'm3-linear': 'var(--md-ref-motion-easing-linear)',
      },
    },
  },
  plugins: [],
};

export default config;
